[project]
name = "calculator-project"
version = "0.1.0"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-v --cov=src --cov-report=term-missing --cov-branch"
testpaths = ["tests"]
